import groovy.json.JsonSlurper

plugins {
    id "java"
    id "idea"
    id "org.wpilib.GradleRIO" version "2027.0.0-alpha-6-kilk"
    id "org.jetbrains.kotlin.jvm" version "2.3.21"
    id "org.jetbrains.kotlin.kapt" version "2.3.21"
    id "java-library"
}
// Disable all simulation and deploy tasks since meanlib is a library
gradle.afterProject { proj ->
    if (proj.name == "meanlib") {
        proj.tasks.configureEach { task ->
            if (task.name.toLowerCase().contains("simulate") ||
                    task.name.toLowerCase().contains("deploy")) {
                task.enabled = false
            }
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

kotlin {
    jvmToolchain(25)
}

wpi.maven.useLocal = false
wpi.maven.useDevelopment = true
wpi.versions.wpilibVersion = '2027.0.0-alpha-6-154-g7d6641b5a'//'2027.+'

group = "org.team2471.lib"

dependencies {
    // using 'api' so other projects inherit the same libraries
    kapt wpi.java.deps.wpilibAnnotations()
    api wpi.java.deps.wpilib()
    api wpi.java.vendor.java()

    api "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0"
    api "org.jetbrains.kotlin:kotlin-stdlib"
    api "org.jetbrains.kotlin:kotlin-reflect"

    api 'com.fasterxml.jackson.core:jackson-databind:2.17.0'
    api 'com.fasterxml.jackson.core:jackson-core:2.17.0'
    api 'com.fasterxml.jackson.core:jackson-annotations:2.17.0'

    def akitFile = file("$projectDir/vendordeps/AdvantageKit.json")
    kapt "org.littletonrobotics.akit:akit-autolog:${new JsonSlurper().parseText(akitFile.text).version}"
}

test {
    useJUnitPlatform()
    systemProperty 'junit.jupiter.extensions.autodetection.enabled', 'true'
}

wpi.java.configureTestTasks(tasks.test)
// Prevent GradleRIO from trying to configure executable tasks
wpi.java.configureExecutableTasks(null)

// Automatically download documentation from libraries
idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += "-XDstringConcat=inline"
}
