import groovy.json.JsonSlurper

plugins {
    id "java"
    id "org.wpilib.GradleRIO" version "2027.0.0-alpha-6"
    id "org.jetbrains.kotlin.jvm" version "2.3.21"
    id "org.jetbrains.kotlin.kapt" version "2.3.21"
    id "idea"
    id "maven-publish"
    id "java-library"
}
// Disable all simulation and deploy tasks since meanlib is a library
gradle.afterProject { proj ->
    if (proj.name == "meanlib") {
        proj.tasks.configureEach { task ->
            if (task.name.toLowerCase().contains("simulate") ||
                    task.name.toLowerCase().contains("deploy")) {
                task.enabled = false
            }
        }
    }
}

group = "org.team2471.lib"

repositories {
    mavenCentral()
}

kotlin {
    jvmToolchain(25)
}

// Automatically download library documentation from libraries
idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}

dependencies {
    // using 'api' so other projects inherit the same libraries
    api wpi.java.deps.wpilibAnnotations()
    api wpi.java.deps.wpilib()
    api wpi.java.vendor.java()

    // Desktop (simulation)
    api wpi.java.deps.wpilibJniDebug(wpi.platforms.desktop)
    api wpi.java.vendor.jniDebug(wpi.platforms.desktop)
    api wpi.sim.enableDebug()

    api wpi.java.deps.wpilibJniRelease(wpi.platforms.desktop)
    api wpi.java.vendor.jniRelease(wpi.platforms.desktop)
    api wpi.sim.enableRelease()

    // SystemCore (robot hardware)
    api wpi.java.deps.wpilibJniDebug(wpi.platforms.systemcore)
    api wpi.java.vendor.jniDebug(wpi.platforms.systemcore)

    api wpi.java.deps.wpilibJniRelease(wpi.platforms.systemcore)
    api wpi.java.vendor.jniRelease(wpi.platforms.systemcore)

    api "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0"
    api "org.jetbrains.kotlin:kotlin-stdlib"
    api "org.jetbrains.kotlin:kotlin-reflect"

    api 'com.fasterxml.jackson.core:jackson-databind:2.17.0'
    api 'com.fasterxml.jackson.core:jackson-core:2.17.0'
    api 'com.fasterxml.jackson.core:jackson-annotations:2.17.0'
}

tasks.test {
    useJUnitPlatform()
    systemProperty "junit.jupiter.extensions.autodetection.enabled", "true"
    testLogging {
        events "passed", "skipped", "failed"
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs += "-XDstringConcat=inline"
}

wpi.java.configureTestTasks(tasks.test)
// Prevent GradleRIO from trying to configure executable tasks
wpi.java.configureExecutableTasks(null)
