package org.team2471.frc.lib.vision

import edu.wpi.first.math.estimator.PoseEstimator
import edu.wpi.first.math.estimator.SwerveDrivePoseEstimator
import edu.wpi.first.math.geometry.Rotation2d
import edu.wpi.first.math.kinematics.SwerveDriveWheelPositions
import org.photonvision.simulation.SimCameraProperties
import org.photonvision.targeting.TargetCorner
import org.team2471.frc.lib.interpolation.SplineInterpolator
import org.team2471.frc.lib.math.*
import org.team2471.frc.lib.motion.following.SwerveDrive
import org.team2471.frc.lib.units.Angle
import org.team2471.frc.lib.units.radians
import kotlin.math.atan
import kotlin.math.pow

/**
 * A curve representing the standard deviation of PhotonVision pose results as a function of distance (in meters).
 * @author Thatcher Moore
 */
val photonStDevDistCurve: SplineInterpolator = SplineInterpolator(
    // dist in meters
    mutableMapOf(
        1.5 to 0.00075,
        1.9 to 0.00125,
        2.5 to 0.003,
        3.0 to 0.0065,
        3.5 to 0.0023,
        4.0 to 0.014,
        4.5 to 0.025, // artificially changed to trust distant tags left. Original: 0.0165
        5.0 to 0.03, // Original: 0.02
        6.0 to 0.04 // Original: 0.03
    )
)

/**
 * The properties of the physical camera on the robot. Since we usually use one type, multiple variables aren't needed
 * @author Thatcher Moore
 */
val cameraProperties = SimCameraProperties().apply {
    setCalibration(1280, 720, Rotation2d.fromDegrees(90.0))
    setCalibError(0.25, 0.08) // Values from docs. Should change
    fps = 20.0 // Complete guess
    avgLatencyMs = 30.0 // complete guess
    latencyStdDevMs = 5.0 // another total guess
}

/**
 * A function that calculates the current pose based on lots of factors. The core of the apriltag sensor fusion.
 *
 * @author Thatcher Moore
 *
 * @param prevAprilTagPos The position generated by this function previously.
 * @param drivePos The most recent position provided by wheel odometry.
 * @param deltaPos Also known as velocity. The difference between the current wheel odometry position and the previous one. Should be a variable in drive
 * @param lookupPose A function, which should be in drive, that can calculate the robot's wheel odometry position at any timestamp.
 * @param driveStDevMeters The standard deviation of the wheel odometry over one frame. (In meters if you cant read the name)
 * @param aprilPoses The list of GlobalPoses you should have gotten from the cameras
 *
 * @return The new calculated AprilTag position. Should be immediately stored in a variable like position in AprilTag
 */
fun getPos(prevAprilTagPos: Vector2L, drivePos: Vector2L, deltaPos: Vector2L, lookupPose: (Double) -> SwerveDrive.Pose?, driveStDevMeters: Double, vararg aprilPoses: GlobalPose): Vector2L {
//                                            measurement, stdev
    val measurementsAndStDevs: MutableList<Pair<Vector2L, Double>> = mutableListOf()

    val testWheelPosition = prevAprilTagPos + deltaPos

    //add drive pose to the list of measurements and standard deviations
    measurementsAndStDevs.add(Pair(testWheelPosition, driveStDevMeters))


    //add camera poses
    for (pose in aprilPoses) {
        try {
            measurementsAndStDevs.add(Pair(pose.latencyAdjustedPose(drivePos, lookupPose), pose.stDev))
        } catch (e: Exception) {
//            println("Stupid thing with latency adjust again")
        }
    }

    // more into here https://docs.google.com/document/d/1FoDFRYyeyxJ-kkqUKKqm2p3dM88hWMFwhrL7IWsKgeM/edit#heading=h.src21s3e4v7y
    var totalPos = Vector2L.Zeros
    var totalStDev = 0.0

    for (posAndStDev in measurementsAndStDevs) {
        val editedStDev = posAndStDev.second.pow(-2)
        totalPos += posAndStDev.first.asMeters.times(editedStDev).meters
        totalStDev += editedStDev
    }
//    if (pos != combinedPosition) {
//        println("WAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
//    }


    //                       breaks apriltags for some reason?
    if (totalStDev != 0.0 /*&& totalStDev < 1000000000.0*/) {
         return totalPos.asMeters.div(totalStDev).meters
//        combinedPosition.coerceIn(Vector2L(0.0.inches, 0.0.inches) + Vector2L(16.0.inches, 16.0.inches), Vector2L(1654.0.cm, 821.0.cm) - Vector2L(16.0.inches, 16.0.inches))
    } else {
        println("Stdev 0.0")
        return testWheelPosition
    }
}

fun PoseEstimator<SwerveDriveWheelPositions>.getPos(): Vector2L {
    return this.estimatedPosition.translation.asVector2().meters
}

fun List<TargetCorner>.getXAngle(hFOV: Angle, hWidth: Double): Angle {
    var centerX = 0.0
    for (i in this) {
        centerX += i.x
    }
    centerX /= this.size

    // Converts the center to be (0,0)
    centerX -= hWidth / 2.0

    return atan((centerX / (hWidth / 2.0)) * (hFOV / 2.0).tan()).radians
}